import { RootState } from './types';
import { combineReducers } from 'redux';
import {
  tab,
  searchingActive,
  account,
  search,
  queue,
  watchers,
  searchOptions,
  sortingOption,
  hitBlocklist,
  timeNextSearch,
  waitingForMturk,
  topticonSettings,
  requesterBlocklist,
  audioSettingsV1,
  selectedHitDbDate,
  hitDatabase,
  dailyEarningsGoal,
  waitingForHitDbRefresh,
  watcherTimers,
  uploadedState,
  expandedSearchResults,
  notificationSettings,
  loggedSearchResults,
  watcherTreeSettings,
  watcherFolders,
  watcherStatistics,
  expandedWatcherFolderIds,
  expandedQueueItems,
  searchAudioEnabled,
  queueSortingOption
} from './reducers/index';

export const rootReducer = combineReducers<RootState>({
  tab,
  queue,
  search,
  account,
  watchers,
  hitDatabase,
  hitBlocklist,
  watcherTimers,
  searchOptions,
  sortingOption,
  uploadedState,
  watcherFolders,
  timeNextSearch,
  audioSettingsV1,
  waitingForMturk,
  searchingActive,
  topticonSettings,
  watcherStatistics,
  dailyEarningsGoal,
  selectedHitDbDate,
  requesterBlocklist,
  queueSortingOption,
  searchAudioEnabled,
  expandedQueueItems,
  watcherTreeSettings,
  loggedSearchResults,
  notificationSettings,
  expandedSearchResults,
  waitingForHitDbRefresh,
  expandedWatcherFolderIds
});
